#!/bin/bash
apt remove docker docker-engine docker.io
apt update
apt install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
apt-key fingerprint 0EBFCD88”
add-apt-repository  "deb [arch=amd64] https://download.docker.com/linux/ubuntu   $(lsb_release -cs)  stable"
apt update
apt-cache madison docker-ce
apt install docker-ce=5:18.09.0~3-0~ubuntu-bionic


